name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 34e11487
      - uses: pnpm/action-setup@v4 # c5ba7f78
      - uses: actions/setup-node@v4 # 49933ea5
        with:
          node-version-file: .nvmrc
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - run: pnpm install --frozen-lockfile
      - run: pnpm ci
      - run: pnpm build
      - name: Validate package
        run: |
          npx publint
          npx attw --pack . --ignore-rules=no-resolution
          pnpm knip
      - run: pnpm publish --provenance --no-git-checks --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: softprops/action-gh-release@v2 # a06a81a0
        with:
          generate_release_notes: true
